version: "3.9"

services:
  gt-vpn-webapp:
    build: .
    container_name: gt-vpn-webapp
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      NODE_ENV: production
